# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.7.2.1
  hooks:
  - id: shellcheck
    exclude: examples/|testing/tests/.*\.sh

- repo: https://github.com/maxwinterstein/shfmt-py
  rev: 3.3.1.8
  hooks:
    - id: shfmt
      exclude: examples/t6.sh
      args: ["-w", "-i", "4", "-ci"]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
    exclude: ^testing/Baseline
  - id: end-of-file-fixer
    exclude: ^testing/Baseline|examples/.*Baseline.*
