name: BTest

on:
  pull_request:
  push:
    branches: [master]


jobs:
  Run-BTest:
    strategy:
      matrix:
        python_version: [3, 3.5]
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
            python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip3 install sphinx==3.5.4
      - run: make test
